Wikia/jira-reporter

reporter/bin/check_php_log.py
reporter/reporters.py
reporter/reports.py
reporter/sources.py
reporter/test/test_php_errors_source.py

* increase the threshold to 20 errors / hour (was 5)
* report function name in issue summary
* remove DB server IP from the report summary
@jcellary

DB errors reporting improved

---

Makefile
reporter/bin/check_php_log.py
reporter/bin/sandbox.py
reporter/helpers.py
reporter/sources.py
reporter/test/test_helpers.py

https://wikia-inc.atlassian.net/browse/PLATFORM-836
Example:
```
<Report: [AjaxPollClass::getVotes] The database query returns 2k rows [DBQueryNoLimit] (da3846e8dcb3fffcc5a618ce6e988b65)>
The database query below returned far too many rows. Please use a proper LIMIT statement.
*Query*: {noformat}SELECT /* AjaxPollClass::getVotes x.x.x.x */  poll_answer  FROM `poll_vote`  WHERE poll_id = '8BD193E3CD923D9F5C6A560FA545F93D'{noformat}
*Function*: AjaxPollClass::getVotes
*Rows returned*: 2215
*Backtrace*:
* /usr/wikia/slot1/3496/src/includes/db/Database.php:3513
* /usr/wikia/slot1/3496/src/includes/db/Database.php:892
* /usr/wikia/slot1/3496/src/includes/db/Database.php:1390
* /usr/wikia/slot1/3496/src/extensions/wikia/AjaxPoll/AjaxPoll_body.php:168
* …
```

Introduce new source for getting queries without the LIMIT statement

---

README.md
reporter/bin/check_php_log.py
reporter/bin/sandbox.py
reporter/sources.py
setup.py

Report not cached GET wikia.php request responses.
Example report:
```
INFO:NotCachedWikiaApiResponsesSource:> Consider caching MercuryApiController::getWikiVariables wikia.php API responses (11544 instances)
<Report: Consider caching WikiaSearchIndexerController::get wikia.php API responses [APIResponsesNotCached] (005b2d7d46a2517e20adf06b38704709)>
The following wikia.php API response can probably be cached on CDN layer (and invalidated when required)
to decrease the load on the backend servers.
*Nirvana controller*: WikiaSearchIndexerController
*Method name*: get
To debug the request run the following command:
{noformat}
curl -svo /dev/null "http://cartoonfatness.wikia.com/wikia.php?controller=WikiaSearchIndexer&format=json&method=get&service=All&ids=25262%7C25262"
{noformat}
```

PLATFORM-899: report not cached wikia.php responses

---

reporter/sources.py
reporter/test/test_helpers.py
reporter/test/test_php_errors_source.py

Normalize `DatabaseBase::sourceFile( /usr/wikia/slot1/3690/src/maintenance/cleanupStarter.sql )` to `DatabaseBase::sourceFile( /maintenance/cleanupStarter.sql )`
Removes duplicates like https://wikia-inc.atlassian.net/browse/ER-5666
@jcellary

Improve DB functions normalization

---

reporter/sources.py
reporter/test/test_php_errors_source.py

Avoid reporting duplicates like https://wikia-inc.atlassian.net/browse/ER-5901 caused by different `N bytes` fragments.
Normalize `Allowed memory size of 536870912 bytes exhausted (tried to allocate 17956864 bytes)` to `Allowed memory size of N bytes exhausted (tried to allocate N bytes)`
@jcellary

Normalize out of memory PHP fatals

---

reporter/helpers.py
reporter/test/test_helpers.py

Improve normalization of queries like the following one:
```sql
SELECT /* ArticleCommentList::getCommentList FooBar... */  page_id,page_title  FROM `page`  WHERE (page_title LIKE 'Foo\_Bar/@comment-%' ) AND page_namespace = '1'  ORDER BY page_id DESC
```
and avoid [duplicates](https://wikia-inc.atlassian.net/browse/ER-5970).
@jcellary

Improve SQL normalization

---

reporter/helpers.py
reporter/test/test_helpers.py

Normalize
```sql
SELECT foo FROM bar WHERE id IN (1,2,3)
```
to
```sql
SELECT foo FROM bar WHERE id IN (XYZ)
```
Avoid the duplicates:
* https://wikia-inc.atlassian.net/browse/ER-6041
* https://wikia-inc.atlassian.net/browse/ER-6042
@jcellary

generalize_sql: improve handling of IN (1,2,3) statements

---

reporter/sources.py
reporter/test/test_php_errors_source.py

As a result of https://wikia-inc.atlassian.net/browse/PLATFORM-1110 we decided to ignore DB deadlocks in Jira reporter as deadlocks are really hard to debug making such reports not actionable.
@jcellary

Do not report DB deadlocks

---

reporter/sources/php.py
reporter/test/test_php_errors_source.py

Remove commas from Kibana URL as it causes to split the query into several subqueries.
https://wikia-inc.atlassian.net/browse/PLATFORM-1221
@idradm / @jcellary

PLATFORM-1221: fix Kibana permalink to a dashboard

---

reporter/sources/common.py
reporter/sources/php.py
reporter/test/test_source.py

https://wikia-inc.atlassian.net/browse/PLATFORM-1162
Most of PHP warnings and fatal errors reported to LogStash do not have the `@fields.url` set which makes Jira tickets reported by our tool lacking a bit of context.
This change introduces a logic (`_has_all_required_field` helper) that tries to find an entry with all required fields (`@fields.url` in this case) to make Jira reports more useful.
@jcellary

PHPErrorsSource: try to report issues with a URL set

---

reporter/sources/php/errors.py
reporter/test/test_php_errors_source.py

https://wikia-inc.atlassian.net/browse/PLATFORM-1463
```
2015-09-11 15:43:36 [INFO] Skipped "PHP Fatal Error: Maximum execution time of 180 seconds exceeded in /includes/cache/MessageCache.php on line 720" (1 occurrences)
2015-09-11 15:43:36 [INFO] Skipped "PHP Fatal error:  Maximum execution time of 180 seconds exceeded in /includes/parser/Preprocessor_DOM.php on line 1105" (1 occurrences)
2015-09-11 15:43:36 [INFO] Skipped "PHP Fatal Error: Allowed memory size of N bytes exhausted (tried to allocate N bytes) in Unknown on line 0" (4 occurrences)
2015-09-11 15:43:36 [INFO] Skipped "PHP Fatal Error: Maximum execution time of 180 seconds exceeded in /includes/parser/Preprocessor_DOM.php on line 0" (1 occurrences)
```
Report all these cases as `PHP Fatal Error`.
PHP, thank you for …

Normalize PHP fatal errors

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/common.py
reporter/sources/php/__init__.py
reporter/sources/php/common.py
reporter/sources/php/db.py
reporter/sources/php/exceptions.py
reporter/test/test_php_exceptions_source.py
reporter/test/test_php_source.py

https://wikia-inc.atlassian.net/browse/PLATFORM-765
Report errors and exceptions logged via `WikiaLogger` - https://kibana.wikia-inc.com/#/dashboard/elasticsearch/Severity%20error
```
INFO:PHPExceptionsSource:Returning 14 reports (with threshold set to 50 applied)
INFO:PHPExceptionsSource:> [Exception] DB readonly mode (531 instances)
INFO:PHPExceptionsSource:> [Error] Phalanx user IP incorrect (41478 instances)
```
+ introduce `PHPLogsSource._normalize_backtrace` and use it in DB errors and exceptions reporter
@jcellary

Process all error messages reported by PHP

---

reporter/sources/php/db.py
reporter/test/test_db_source.py

https://wikia-inc.atlassian.net/browse/PLATFORM-1512
Use function name (from the exception message) instead of the SQL query when normalizing DB errors with error code set to `ER_PARSE_ERROR`.
This will give us an automated source for tracking SQL injections tries.
Additionally, add test cases for `DBQueryErrorsSource` class.
@jcellary / @Grunny

PLATFORM-1512 improve how we normalize SQL parse errors to catch SQL injection tries

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/reports.py
reporter/sources/common.py
reporter/sources/pandora/errors.py
reporter/sources/php/assertions.py
reporter/sources/php/db.py
reporter/sources/php/errors.py
reporter/sources/php/exceptions.py
reporter/sources/pt_kill.py
reporter/test/test_php_exceptions_source.py

Code cleanup: introduce `_get_kibana_url` method for `KibanaSource` subclasses that generate a URL to a custom Kibana dashboard.
* Generate more "precise" Kibana dashboards showing only the current issue
* Improve elasticsearch query and normalization in `PHPExceptionsSource`
Example: https://kibana.wikia-inc.com/index.html#/dashboard/script/logstash.js?query=@exception.class:%20%22DBQueryError%22%20AND%20%22SDFilter:createTempTable%22&from=6h&fields=@timestamp,@source_host,@context.errno,@context.err,@fields.db_name,@fields.url
@jcellary

Improve Kibana URL generation

---

reporter/bin/sandbox.py
reporter/sources/common.py
reporter/sources/php/__init__.py
reporter/sources/php/common.py
reporter/sources/php/security.py
reporter/test/test_php_source.py

https://wikia-inc.atlassian.net/browse/PLATFORM-1535
Automate reporting of CSRF issues that are logged by [PLATFORM-1540](https://wikia-inc.atlassian.net/browse/PLATFORM-1540) - f817287
Not enabling it in `check.py` (only in `sandbox.py`) - waiting for more detailed logging that will go live Oct 12th.
@jcellary

PLATFORM-1535: automate security issues reporting

---

reporter/sources/common.py
reporter/sources/php/db.py
reporter/sources/php/exceptions.py
reporter/test/test_db_source.py
reporter/test/test_php_errors_source.py
reporter/test/test_php_exceptions_source.py

Properly encode UTF strings and avoid `UnicodeEncodeError`
@jcellary

Improve UTF handling

---

reporter/helpers.py
reporter/test/test_helpers.py

Include PHP logs emitted by deploy tools servers (running in SJC and RES) when checking PHP warnings.

Do not ignore deploy hosts when checking PHP logs

---

reporter/bin/sandbox.py
reporter/sources/common.py
reporter/sources/php/errors.py
reporter/test/test_kibana.py
reporter/test/test_php_errors_source.py

Improve the way warnings like `PHP Warning: DOMDocument::loadHTML(): Opening and ending tag mismatch: td and tr in Entity, line: 46 in /includes/wikia/parser/templatetypes/handlers/DataTables.class.php on line 81` ([ER-9977](https://wikia-inc.atlassian.net/browse/ER-9977)) are normalized
And add a link to request trace based on `@fields.request_id`.

Remove DOMDocument::loadHTML() errors details

---

reporter/reporters.py
reporter/reports.py
reporter/sources/common.py

@JoannaBorun added the URL custom field to tickets in ER project. Let's use this field to store the URL of the page where the report issue can be reproduced.
And as we're here, do not set `report_hash` custom field - the unique report hash is now a part of ticket description.
@jcellary

Set URL JIRA field when reporting issues

---

reporter/sources/php/errors.py
reporter/test/test_php_errors_source.py

[PLATFORM-1931](https://wikia-inc.atlassian.net/browse/PLATFORM-1931)
PHP reports `PHP Fatal Error: Maximum execution time of 180 seconds exceeded in /lib/vendor/simplehtmldom/simple_html_dom.php on line 139` for various lines. Let's improve the message normalization and ignore the line number in this case.
@rogatty / @jcellary

PLATFORM-1931: normalize simple_html_dom fatals

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/php/errors.py
reporter/test/test_php_errors_source.py

We managed to keep the log of PHP fatals and exceptions quite silent for a while. Now the time has come to get rid of PHP notices (when there are more than 2000 reports an hour).
```
PHP Notice: Undefined index: X in /extensions/wikia/ArticleAsJson/ArticleAsJson.class.php on line 419 (10934 instances)
```
@jcellary

Report PHP notices

---

reporter/sources/common.py
reporter/test/test_php_errors_source.py

[PLATFORM-2032](https://wikia-inc.atlassian.net/browse/PLATFORM-2032)
https://github.com/Wikia/app/pull/9878 changed the way page URL is reported to ELK. Let's update Jira Reporter to handle the new context schema.
@jcellary

PLATFORM-2032: Use new url field

---

reporter/sources/php/assertions.py
reporter/sources/php/db.py
reporter/sources/php/errors.py
reporter/sources/php/exceptions.py
reporter/sources/php/security.py
reporter/test/test_php_errors_source.py
reporter/test/test_source.py

[PLATFORM-1949](https://wikia-inc.atlassian.net/browse/PLATFORM-1949) introduced a new set of fields for logging page URL and domain. Update Jira Reporter to use them for filtering and when generating Kibana dashboard URL.
See https://github.com/Wikia/app/pull/9878 / #39
@jcellary

PLATFORM-1949: Use @fields.http_url

---

reporter/reporters.py

```
jira.exceptions.JIRAError: HTTP 400: "The entered text is too long. It exceeds the allowed limit of 255 characters."
```
@jcellary

Handle jira.exceptions.JIRAError

---

reporter/sources/common.py

Prevent the following:
```
2016-04-26 11:05:26 kibana                              INFO     58 rows returned in 32 ms
Traceback (most recent call last):
File "reporter/bin/check.py", line 36, in <module>
reports += DBQueryErrorsSource().query(threshold=20)
File "/opt/jira-reporter/reporter/sources/common.py", line 34, in query
entries = [entry for entry in self._get_entries(query) if self._filter(entry)]
File "/opt/jira-reporter/reporter/sources/php/db.py", line 48, in _filter
additional_context = self._get_context_from_entry(entry)
File "/opt/jira-reporter/reporter/sources/php/db.py", line 171, in _get_context_from_entry
'error': '{} {}'.format(context.get('errno'), context.get('err', '').encode('utf-8')),
AttributeError: 'list' object has no attribute 'get'
```
@jcellary

Source: handle exceptions raised in _get_entries or _filter

---

reporter/sources/php/assertions.py
reporter/test/test_php_assertions_source.py

https://wikia-inc.atlassian.net/browse/MAIN-8330
```python
assert self._source._normalize({
'@exception': {'message': "API call to 10.8.42.49:31141/user/5473454/attr/occupation failed: Operation timed out after 5003 milliseconds with 0 bytes received"}
}) == 'None-API call to N.N.N.N:N/user/N/attr/X failed: Operation timed out after N milliseconds with N bytes received'
```
@garthwebb, thanks for reporting this :)

	PHPAssertionsSource: normalize user attributes URLs and timeout errors (ms and bytes)

---

reporter/sources/php/execution_timeouts.py

PHP timeouts were not reported because of spaces in the report's label

Proper label for PHP timeout reporter

---

.gitignore
reporter/classifier/config/components.yaml
reporter/classifier/config/extensions.csv
reporter/classifier/config/paths.yaml

When we have an error in Discussions extension assign the Discussions component to the ticket.
/cc @Wikia/iris

Discussions extension -> Discussions component

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/indexdigest/__init__.py
reporter/sources/indexdigest/indexdigest.py

Resolves #82 
```
2018-01-02 14:22:58 IndexDigestSource                   INFO     Got 6 entries after filtering
2018-01-02 14:22:58 IndexDigestSource                   INFO     Returning 4 reports (with threshold set to 1 applied)
2018-01-02 14:22:58 IndexDigestSource                   INFO     > ab_experiment_group_ranges | "version_id" index can be removed as redundant (covered by "PRIMARY") (2 instances)
2018-01-02 14:22:58 IndexDigestSource                   INFO     > valid_tag | "valid_tag" has just a single column (1 instances)
2018-01-02 14:22:58 IndexDigestSource                   INFO     > page_restrictions | "pr_page" index can be removed as redundant (covered by "PRIMARY") (1 instances)
2018-01-02 14:22:58 IndexDigestSource                   INFO     > global_watchlist | …
```

SUS-3566 | index-digest - integrate with Jira Reporter

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/php/__init__.py
reporter/sources/php/db.py

https://wikia-inc.atlassian.net/browse/SUS-5133
```
2018-06-08 10:24:48 DBReadQueryOnMaster                 INFO     Returning 14 reports (with threshold set to 1 applied)
2018-06-08 10:24:48 DBReadQueryOnMaster                 INFO     > [WikiFactory::getVariables] The database query should be moved to slave or an offline task (1 instances)
2018-06-08 10:24:48 DBReadQueryOnMaster                 INFO     > [WikiFactory::setVarById] The database query should be moved to slave or an offline task (3 instances)
2018-06-08 10:24:48 DBReadQueryOnMaster                 INFO     > [User::saveSettings] The database query should be moved to slave or an offline task (1 instances)
2018-06-08 10:24:48 DBReadQueryOnMaster                 INFO     > [WikiFactory::loadVariableFromDB (from …
```

SUS-5138 | Report methods performing queries on database master when handling GET requests

---

reporter/sources/php/errors.py
reporter/test/test_php_errors_source.py

```
PHP Warning: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 2279.
--enable-fd-setsize=3072 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in /usr/wikia/slot1/23724/src/includes/objectcache/MemcachedClient.php on line 1359
```

PHPErrorsSource: normalize memcache client errors

---

reporter/helpers.py
reporter/sources/backend/backend.py
reporter/sources/caching.py
reporter/sources/helios.py
reporter/sources/php/assertions.py
reporter/sources/php/db.py
reporter/sources/php/errors.py
reporter/sources/php/exceptions.py
reporter/sources/php/execution_timeouts.py
reporter/sources/php/security.py
reporter/sources/php/triggers.py
reporter/test/test_db_source.py
reporter/test/test_helpers.py
reporter/test/test_php_errors_source.py
reporter/test/test_php_exceptions_source.py

https://wikia-inc.atlassian.net/browse/SUS-5451
Use `@fields.environment` to check if a log entry comes from production / verify / preview instead of checking `@source_host` (which is not set when MediaWiki logs from Kubernetes).

SUS-5451 | handle logs from Kubernetes

---

reporter/bin/sandbox.py
reporter/helpers.py
reporter/sources/helios.py
reporter/test/test_helios_source.py
reporter/test/test_helpers.py

Helios now runs on Kubernetes - use a different Elastic Search query to get the logs.

Helios: fix how logs are analysed

---

reporter/sources/pandora/errors.py
reporter/test/test_pandora_errors_source.py

https://wikia-inc.atlassian.net/browse/SUS-5480
The following tickets will be reported:
```
...
2018-07-06 09:52:08 PandoraErrorsSource                 INFO     > [geoip] Unable to report to InfluxDB with error 'Server returned HTTP response code: 400 for URL: http://prod.os-metrics-db.service.sjc.consul:8086/write?db=services&precision=m with content :'Bad Request''. Discarding data. (600 instances)
2018-07-06 09:52:08 PandoraErrorsSource                 INFO     > [user-registration-feed] Unable to report to InfluxDB with error 'Server returned HTTP response code: 400 for URL: http://dev.os-metrics-db.service.poz-dev.consul:8086/write?db=services&precision=m with content :'Bad Request''. Discarding data. (118 instances)
2018-07-06 09:52:08 PandoraErrorsSource                 INFO     > …
```

SUS-5480 | Error reporter should include service name when matching failure logs

---

reporter/sources/indexdigest/indexdigest.py
reporter/test/test_indexdigest.py

Take report message into account, this improves reporting of duplicated indices (a single table can have many reports on that)
An example: https://wikia-inc.atlassian.net/browse/SER-1773?focusedCommentId=422843&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-422843

SUS-1773 | improve index_digest reports normalisation

---

reporter/bin/check.py
reporter/sources/__init__.py
reporter/sources/ucp/__init__.py
reporter/sources/ucp/errors.py

Add basic logic to report PHP errors, fatals and uncaught exceptions from UCP,
based on the existing logic we had for app. We can monitor the results in the
coming days and adjust thresholds and normalization if needed.

Add initial UCP reporting

---

reporter/sources/common.py
reporter/sources/ucp/errors.py
reporter/test/resources/ucp_error_titles.json
reporter/test/test_ucp_errors_source.py

* https://wikia-inc.atlassian.net/browse/PLATFORM-5310
Currently we generate unique hash based on whole description which have urls, wiki ID etc. This causes many duplicates reported as issues. We should remove those variables before generating hashes, and this should allow to detect more duplicates.
@Wikia/core-platform-team

PLATFORM-5310 | Set correct unique_id hash for UCP issues

---

docker/cronjob.yaml

This is part of migration from PodSecurityPolicy to the PodSecurity Admission Controller [1]. Some security parameters which are implicitly injected by PodSecurityPolicy mutating admission webhooks, need to be explicitly set to be compliant with Pod Security Standards [2].
Adding those security parameters don't change how workload is functioning because currently they are injected into manifest spec during Pod creation.
[1] https://fandom.atlassian.net/browse/OPS-13747
[2] https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

Set explicitly security context to be compliant with Pod Security Standards

---

docker/cronjob.yaml

Old version throws:
```
❯ kubectl --context=kube-sjc-prod --namespace=prod apply --filename=docker/cronjob.yaml
error: resource mapping not found for name: "jira-reporter" namespace: "" from "docker/cronjob.yaml": no matches for kind "CronJob" in version "batch/v1beta1"
ensure CRDs are installed first
```
New API version:
```
❯ kubectl --context=kube-sjc-prod --namespace=prod apply --filename=docker/cronjob.yaml
cronjob.batch/jira-reporter created
```

Update k8s API version for CronJob deploy error
