Wikia/jira-reporter

reporter/bin/check_php_log.py

PLATFORM-839: report strict and catchable fatals

---

reporter/sources.py
reporter/test/test_php_errors_source.py

An example: https://wikia-inc.atlassian.net/browse/MAIN-4149
@jcellary

PLATFORM-1020: add a link to Kibana dashboard with PHP error log entries

---

reporter/sources.py
reporter/test/test_php_errors_source.py

Avoid duplicates:
* https://wikia-inc.atlassian.net/browse/ER-6175
* https://wikia-inc.atlassian.net/browse/ER-6176
* https://wikia-inc.atlassian.net/browse/ER-6177
* https://wikia-inc.atlassian.net/browse/ER-6178
...
@jcellary

PHPErrorsSource: normalize "unmatched parentheses at offset N"

---

reporter/sources.py
reporter/test/test_php_errors_source.py

See #11
Do not report issues like this one: https://wikia-inc.atlassian.net/browse/ER-6196
@jcellary

Skip "Lock wait timeout exceeded" errors

---

reporter/helpers.py
reporter/sources/caching.py
reporter/sources/common.py
reporter/sources/php.py
reporter/test/test_helpers.py
reporter/test/test_php_errors_source.py

The Jira Reporter tool was reporting issues from SJC only. Report Reston issues as well.
https://wikia-inc.atlassian.net/browse/PLATFORM-1315
@michalroszka / @jcellary

Report issues in SJC and Reston separately

---

reporter/bin/check_php_log.py
reporter/bin/sandbox.py
reporter/reports.py
reporter/sources/__init__.py
reporter/sources/common.py
reporter/sources/pandora/__init__.py
reporter/sources/pandora/common.py
reporter/sources/pandora/errors.py
reporter/test/test_kibana.py
reporter/test/test_pandora_errors_source.py

https://wikia-inc.atlassian.net/browse/PLATFORM-1420
```
INFO:PandoraErrorsSource:Got 4160 entries after filtering
INFO:PandoraErrorsSource:Returning 6 reports (with threshold set to 5 applied)
```
Example report:
```
h3. ERROR: Unable to get the user information for userId: 23912489, Returning the default.
*App name*: {{discussion}}
*Logger name*: {{com.wikia.discussionservice.services.AggregationService}}
*Thread name*: {{dw-11324 - GET /3035/forums/3035?limit=20&page=0&responseGroup=small&sortDirection=ascending&sortKey=creation_date}}
h3. Stacktrace
{code}
org.json.JSONException: JSONObject["items"] not found.
at org.json.JSONObject.get(JSONObject.java:473) ~[json-20140107.jar:na]
at com.wikia.discussionservice.services.AggregationService.getUserInfo(AggregationService.java:237) …
```

Setup automated reporting of Services code issues using Jira Reporter

---

reporter/sources/php/exceptions.py
reporter/test/test_pandora_errors_source.py
reporter/test/test_php_exceptions_source.py

* [ER-7632](https://wikia-inc.atlassian.net/browse/ER-7632) - `[Exception] Server #3 (10.8.38.41) is excessively lagged (126 seconds)`
* [ER-7551](https://wikia-inc.atlassian.net/browse/ER-7551) - `[pandora-indexer-base] Read timed out reading GET http://dailylifewithamonstergirl.wikia.com/wiki/Centorea_Shianus?action=raw`
* [ER-7556](https://wikia-inc.atlassian.net/browse/ER-7556) - `Template file not found: /usr/wikia/slot1/6969/src/extensions/wikia/Rail/templates/RailController_LazyForAnons.php`
Improves #22 and #19 
@jcellary / @michalroszka

Improve PHP and Pandora errors normalization

---

reporter/sources/common.py
reporter/sources/php/assertions.py
reporter/sources/php/security.py
reporter/test/test_kibana.py

And encode backslashes in Kibana links
@jcellary

PHPSecuritySource: make Kibana links actually work and be more precise

---

reporter/sources/php/errors.py
reporter/test/test_php_errors_source.py

https://wikia-inc.atlassian.net/browse/ER-9495

PHPErrorsSource: improve normalization of messages with full stack trace

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/phalanx.py
reporter/test/test_phalanx_source.py

[SUS-54](https://wikia-inc.atlassian.net/browse/SUS-54)
Let's check Phalanx logs for messages that have WARN+ level and report them as Jira tickets.
@Wikia/sustaining-team

PhalanxSource: check Phalanx service logs

---

reporter/sources/common.py

See https://github.com/Wikia/app/pull/9878
@jcellary

KibanaSource: support @fields.trace_id introduced by PLATFORM-1949

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/mercury/__init__.py
reporter/sources/mercury/common.py
reporter/sources/mercury/fatals.py

[PLATFORM-2055](https://wikia-inc.atlassian.net/browse/PLATFORM-2055)
Report errors matching `severity: "fatal" AND name: "mercury" AND @source_host: /mercury-(s|r).*/`
@jcellary / @rogatty

As a developer I want Error Reporter to report fatal errors in Mercury

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/mercury/__init__.py
reporter/sources/mercury/common.py
reporter/sources/mercury/fatals.py

[PLATFORM-2078](https://wikia-inc.atlassian.net/browse/PLATFORM-2078) / a follow-up of #40
Report both fatals (no threshold) and errors (at least 50 entries per hour) logged by Mercury back-end. And include staging machines.
@jcellary / @hakubo

PLATFORM-2078: report Mercury fatals and errors

---

reporter/sources/common.py
reporter/test/test_php_errors_source.py

staging-s1 is now our new preview

---

reporter/sources/common.py
reporter/test/test_helpers.py
reporter/test/test_php_errors_source.py

New preview/verify servers

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/helpers.py
reporter/sources/__init__.py
reporter/sources/helios.py
reporter/test/test_helios_source.py

[PLATFORM-2135](https://wikia-inc.atlassian.net/browse/PLATFORM-2135)
Report Helios problems as JIRA tickets.
@sqreek / @ArturKlajnerok / @jcellary

PLATFORM-2135: report Helios errors

---

reporter/bin/check.py
reporter/sources/__init__.py
reporter/sources/vignette/__init__.py
reporter/sources/vignette/thumbs.py
reporter/test/test_vignette_thumbs_source.py

[Ticket](https://wikia-inc.atlassian.net/browse/SER-81)
This PR adds a reporter for thumbnail verification errors.

SER-81 add reporter for Vignette

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/anemometer/README.md
reporter/sources/anemometer/__init__.py
reporter/sources/anemometer/anemometer.py
reporter/sources/anemometer/client.py

[PLATFORM-2180](https://wikia-inc.atlassian.net/browse/PLATFORM-2180)
Use [Anemometer](http://dev-drozdo/anemometer) to get the list of queries which performance can optimized.
Let's set the initial thresholds and only report queries that either:
* has median query time greater than 500 ms
* summarized query time over time is greater than 300 sec
Pinging @drozdo & @jcellary

PLATFORM-2180: Introduce AnemometerClient and reporter

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/php/exceptions.py

[PLATFORM-2271](https://wikia-inc.atlassian.net/browse/PLATFORM-2271)
@rogatty

	Report exceptions logged with "critical" severity without a threshold

---

reporter/bin/sandbox.py
reporter/sources/anemometer/anemometer.py

[OPS-9159](https://wikia-inc.atlassian.net/browse/OPS-9159)
@drozdo

OPS-9159: new anemometer host is opstools-s1

---

reporter/sources/phalanx.py
reporter/test/test_phalanx_source.py

Less noise in Jira tickets
An example ticket: [ER-14575](https://wikia-inc.atlassian.net/browse/ER-14575)

Phalanx: remove X-Request-Id from a normalized message

---

reporter/bin/sandbox.py
reporter/sources/common.py
reporter/sources/phalanx.py
reporter/test/test_phalanx_source.py

* improved normalization of Phalanx errors
* Kibana link to a dashboard with specific trace ID logs
@mixth-sense

Phalanx link to trace

---

reporter/reporters.py

This will allow us to quickly check if a ticket is still valid, ER date will tell us when was the last time log entries for a given ticket were there
See https://github.com/Wikia/chef-repo/pull/11287 for config update (custom field definition).
@jcellary / @JoannaBorun

PLATFORM-2441: set "ER date" custom field

---

reporter/reporters.py

If a ticket is still valid (i.e. we're getting entries in logs), but is now closed (but not as "Won't Fix" or "Duplicate") for more than 14 days, let's reopen it and add a comment.
See https://wikia-inc.atlassian.net/browse/SUS-1134
@JoannaBorun / @TK-999

SUS-1134: reopen still valid reports

---

reporter/reporters.py

https://wikia-inc.atlassian.net/browse/SUS-1168
@hakubo / @mixth-sense

SUS-1168: do not update ER date for tickets closed as "Won't Fix" or "Duplicate"

---

reporter/sources/php/security.py

Update link to CSRF documentation

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/classifier/classifier.py
reporter/sources/__init__.py
reporter/sources/chat/__init__.py
reporter/sources/chat/chat.py
reporter/sources/common.py
setup.py

also i've removed PerfMonitoring dependency
@macbre

Norsk skogkatt for Chat server :D

---

reporter/bin/check.py
reporter/sources/mercury/fatals.py

https://wikia-inc.atlassian.net/browse/XW-2867
Ping @macbre @rogatty

XW-2867 | Fix mercury emergency label + add mobile-wiki reporting

---

reporter/bin/sandbox.py
reporter/sources/php/exceptions.py
reporter/test/test_php_exceptions_source.py

https://wikia-inc.atlassian.net/browse/SUS-1768
https://github.com/Wikia/app/pull/12536 unifies the way MediaWiki logs un-handled exceptions, let's improve reporting of them by Jira Reporter
@TK-999

Sus 1768 improve exceptions reporting

---

reporter/sources/chat/chat.py
reporter/sources/common.py
reporter/sources/mercury/common.py
reporter/sources/php/security.py
reporter/test/test_kibana.py
reporter/test/test_php_errors_source.py
setup.py

https://wikia-inc.atlassian.net/browse/SUS-2111 + https://github.com/Wikia/chat/pull/45
And decrease a default limit to `10000` rows.

SUS-2111: use ES5 compatible client

---

reporter/sources/php/errors.py
reporter/test/test_php_errors_source.py

```
PHP Notice: Undefined index:  in /includes/StringUtils.php on line 261
PHP Warning:  Error while sending QUERY packet. PID=21637 in /includes/db/DatabaseMysqli.php on line 44
```

Improve normalization of PHP notices / warnings

---

reporter/bin/check.py
reporter/classifier/classifier.py
reporter/reporters.py
reporter/sources/php/__init__.py
reporter/sources/php/execution_timeouts.py

https://wikia-inc.atlassian.net/browse/SUS-2052
This PR adds a reporter for PHP execution timeouts. Since this is usually caused by extremely large articles, the tickets should be sent to ComSup for investigation.
@mixth-sense @macbre

SUS-2052 added php execution timeout reporter

---

reporter/sources/pandora/errors.py

use kubernetes.labels.type: pandora to recognize pandora logs

---

reporter/sources/pandora/common.py

pandora need to use logstash-* index

---

reporter/sources/pandora/common.py

use logstash-* for pandora services

---

reporter/classifier/classifier.py
reporter/test/test_classifier.py

Jira will move them to appropriate projects based on a label and Jira workflow.

PandoraErrorsSource: route Pandora issues to ER project in Jira

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/classifier/classifier.py
reporter/helpers.py
reporter/sources/__init__.py
reporter/sources/backend/__init__.py
reporter/sources/backend/backend.py
reporter/test/test_backend_source.py
reporter/test/test_classifier.py
reporter/test/test_helpers.py

https://wikia-inc.atlassian.net/browse/SUS-3449

SUS-3449 | introduce BackendSource

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/php/__init__.py
reporter/sources/php/triggers.py

https://wikia-inc.atlassian.net/browse/SUS-3469
See Wikia/app#14343

SUS-3469 | introduce PHPTriggeredSource

---

reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/pipe/__init__.py
reporter/sources/pipe/pipe.py

Create a generic source that will file tickets using reports pushed to `logstash-jira-reporter-pipe` es index. So far the only client is `sus-dynks` repo -https://github.com/Wikia/sus-dynks/blob/master/linters/check_maintenance_scripts.py
```
2018-02-02 13:03:08 elasticsearch                       INFO     GET http://logs-prod.es.service.sjc.consul:9200/logstash-jira-reporter-pipe-2018.02.01,logstash-jira-reporter-pipe-2018.02.02/_search?sort=_doc&sc
roll=5m&size=1000 [status:200 request:1.035s]
2018-02-02 13:03:08 elasticsearch                       INFO     GET http://logs-prod.es.service.sjc.consul:9200/_search/scroll?scroll=5m [status:200 request:0.201s]
2018-02-02 13:03:08 kibana                              INFO     4 rows returned
2018-02-02 13:03:08 ReportsPipeSource …
```

SUS-3882 | introduce ReportsPipeSource

---

setup.py

See https://github.com/macbre/wikia-common-kibana/pull/2

Use wikia-common-kibana==2.2.4

---

Makefile
reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/php/__init__.py
reporter/sources/php/errors.py
reporter/sources/php/exceptions.py
reporter/test/test_php_exceptions_source.py

https://wikia-inc.atlassian.net/browse/SUS-5243

SUS-5243 | introduce PHPTypeErrorsSource

---

reporter/bin/sandbox.py
reporter/classifier/config/extensions.csv
reporter/classifier/config/paths.yaml
reporter/sources/__init__.py
reporter/sources/mysql_kill.py
setup.py

https://wikia-inc.atlassian.net/browse/SUS-5511

SUS-5511 | introduce mysql-killer source

---

Makefile
reporter/bin/check.py
reporter/bin/sandbox.py
reporter/sources/__init__.py
reporter/sources/kubernetes/__init__.py
reporter/sources/kubernetes/backoff.py
reporter/sources/kubernetes/common.py
reporter/test/test_k8s_backoff_source.py

https://wikia-inc.atlassian.net/browse/SUS-6261
```
Time | eventMessage | involvedObject.name
  | November 16th 2018, 03:36:14.000 | Job has reached the specified backoff limit | sla-report-comdev-1542331800
  | November 16th 2018, 02:36:13.000 | Job has reached the specified backoff limit | sla-report-comdev-1542331800
  | November 15th 2018, 22:27:54.000 | Job has reached the specified backoff limit | mw-cj-founder-emails-days-passed-1542313200
  | November 15th 2018, 21:27:43.000 | Job has reached the specified backoff limit | mw-cj-founder-emails-days-passed-1542313200
  | November 15th 2018, 17:23:44.000 | Job has reached the specified backoff limit | thumblr-image-comparison
  | November 15th 2018, 16:22:27.000 | Job has reached the specified backoff limit | thumblr-image-comparison …
```

SUS-6261 | k8s - report "Job has reached the specified backoff limit"

---

reporter/sources/anemometer/anemometer.py

Anemometer has moved so we should start using the new host in configuration.

Fix anemometer host

---

Makefile
docker/cronjob.yaml

0.0.40 is causing errors for some reason, need to debug

downgrade vault init container back to 0.0.37

---

reporter/sources/ucp/errors.py

\\\\\\\\\\\\\\\\\\\\\ \\\\\\\\\\\\\\\\\\ \\\\\\\\\\\\\\\\\\ \\\\\\\\\\\\\\\\\\
\\\\\\\\\\\\\\\\\\\ \\\\\\\\\\\\\\\\\\  \\\\\\\\\\\\\\\\\\  \\\\\\\\\\\\\\\\\\.
\\\\\\\\\\\\\\\\\\:
- \\\\\\\\\\\\\\\\\\
- \\\\\\\\\\\\\\\\\\

\\\\\\\\\\\\\\\\\\

---

docker/cronjob.yaml

https://wikia-inc.atlassian.net/browse/OPS-12936

Increase ownership visibility across k8s objects
